### ISSUE TITLE
获取不到配置文件信息。

### ISSUE THREAD

**Issue by WangJunZzz** [pengweiqhca/Microsoft.Extensions.Configuration.ValueBinder#1]
services.ConfigureJsonValue<ConfigMsg>("ConfigOptions"); 
![image](https://user-images.githubusercontent.com/25657426/64932938-efa6c200-d874-11e9-9ab5-b5741a90674c.png)
这样获取不到阿波罗配置文件中的信息，那里有问题吗？
Dotnet Core2.2

**Comment by pengweiqhca** [comment]
这个只是绑定啊，你需要使用ioptions<>

**Comment by WangJunZzz** [comment]
> 这个只是绑定啊，你需要使用ioptions<>
   services.ConfigureJsonValue<ConfigMsg>("ConfigOptions");
这样？

**Comment by WangJunZzz** [comment]
services.ConfigureJsonValue<ConfigMsg>("ConfigOptions");
这样吗？

**Comment by WangJunZzz** [comment]
services.ConfigureJsonValue <ConfigMsg> ("ConfigOptions"); 这样？

**Comment by WangJunZzz** [comment]
![image](https://user-images.githubusercontent.com/25657426/64938364-31913180-d890-11e9-9b70-c567e011ee5f.png)
这样获取不到

**Comment by pengweiqhca** [comment]
是注入`IOptions<ConfigMsg>`，具体看https://docs.microsoft.com/zh-cn/aspnet/core/fundamentals/configuration/options

**Comment by WangJunZzz** [comment]
也获取不到
![image](https://user-images.githubusercontent.com/25657426/65005865-f21c2100-d933-11e9-8a82-f585a921792a.png)

**Comment by pengweiqhca** [comment]
那你先确定IConfigration["ConfigOptions"]是否有值

**Comment by WangJunZzz** [comment]
可以获取到了，但是原生的dotnet core 再注入的时候 ,不需要使用 IOptions<ConfigMsg> 直接注入ConfigMsg就好了。所以采用你的这个 需要config.values.xx才能获取。
![image](https://user-images.githubusercontent.com/25657426/65006633-3ad4d980-d936-11e9-9e1a-df12647b9303.png)

**Comment by WangJunZzz** [comment]
![image](https://user-images.githubusercontent.com/25657426/65006717-7ec7de80-d936-11e9-8243-be56b1c6fe8d.png)
这是采用你的这个获取方式，如果是旧项目改造就需要改很多地方了。

**Comment by pengweiqhca** [comment]
config = configMsg.Value
